# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/electrik/Documents/GitHub/libcnary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/electrik/Documents/GitHub/libcnary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/electrik/Documents/GitHub/libcnary/CMakeFiles /Users/electrik/Documents/GitHub/libcnary//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/electrik/Documents/GitHub/libcnary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libcnary

# Build rule for target.
libcnary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcnary
.PHONY : libcnary

# fast build rule for target.
libcnary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/build
.PHONY : libcnary/fast

iterator.o: iterator.c.o
.PHONY : iterator.o

# target to build an object file
iterator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/iterator.c.o
.PHONY : iterator.c.o

iterator.i: iterator.c.i
.PHONY : iterator.i

# target to preprocess a source file
iterator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/iterator.c.i
.PHONY : iterator.c.i

iterator.s: iterator.c.s
.PHONY : iterator.s

# target to generate assembly for a file
iterator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/iterator.c.s
.PHONY : iterator.c.s

list.o: list.c.o
.PHONY : list.o

# target to build an object file
list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/list.c.o
.PHONY : list.c.o

list.i: list.c.i
.PHONY : list.i

# target to preprocess a source file
list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/list.c.i
.PHONY : list.c.i

list.s: list.c.s
.PHONY : list.s

# target to generate assembly for a file
list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/list.c.s
.PHONY : list.c.s

node.o: node.c.o
.PHONY : node.o

# target to build an object file
node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node.c.o
.PHONY : node.c.o

node.i: node.c.i
.PHONY : node.i

# target to preprocess a source file
node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node.c.i
.PHONY : node.c.i

node.s: node.c.s
.PHONY : node.s

# target to generate assembly for a file
node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node.c.s
.PHONY : node.c.s

node_iterator.o: node_iterator.c.o
.PHONY : node_iterator.o

# target to build an object file
node_iterator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node_iterator.c.o
.PHONY : node_iterator.c.o

node_iterator.i: node_iterator.c.i
.PHONY : node_iterator.i

# target to preprocess a source file
node_iterator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node_iterator.c.i
.PHONY : node_iterator.c.i

node_iterator.s: node_iterator.c.s
.PHONY : node_iterator.s

# target to generate assembly for a file
node_iterator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node_iterator.c.s
.PHONY : node_iterator.c.s

node_list.o: node_list.c.o
.PHONY : node_list.o

# target to build an object file
node_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node_list.c.o
.PHONY : node_list.c.o

node_list.i: node_list.c.i
.PHONY : node_list.i

# target to preprocess a source file
node_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node_list.c.i
.PHONY : node_list.c.i

node_list.s: node_list.c.s
.PHONY : node_list.s

# target to generate assembly for a file
node_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcnary.dir/build.make CMakeFiles/libcnary.dir/node_list.c.s
.PHONY : node_list.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libcnary"
	@echo "... iterator.o"
	@echo "... iterator.i"
	@echo "... iterator.s"
	@echo "... list.o"
	@echo "... list.i"
	@echo "... list.s"
	@echo "... node.o"
	@echo "... node.i"
	@echo "... node.s"
	@echo "... node_iterator.o"
	@echo "... node_iterator.i"
	@echo "... node_iterator.s"
	@echo "... node_list.o"
	@echo "... node_list.i"
	@echo "... node_list.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

